# 06 - Extraction de caractéristiques pour le Machine Learning

## Objectif

Transformer les images en dataset tabulaire exploitable par un modèle de Machine Learning classique comme SVM.

In [1]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent
sys.path.append(str(PROJECT_ROOT))

import pandas as pd

from src.features import build_features_dataframe, get_feature_columns
from src.utils import FEATURES_DIR, build_image_index, save_dataframe

## 1. Index des images

Chaque ligne représente une image avec son chemin, son split et son label.

In [2]:
index_df = build_image_index()

if index_df.empty:
    raise FileNotFoundError("Aucune image trouvée dans data/raw/casting_data/.")

display(index_df.head())
print(f"Nombre d'images : {len(index_df)}")

,path,filename,split,class_folder,label,label_name
0,C:\Users\espacegamers\Desktop\Master IAII\Cour...,cast_ok_0_1.jpeg,train,ok_front,0,OK
1,C:\Users\espacegamers\Desktop\Master IAII\Cour...,cast_ok_0_1001.jpeg,train,ok_front,0,OK
2,C:\Users\espacegamers\Desktop\Master IAII\Cour...,cast_ok_0_1002.jpeg,train,ok_front,0,OK
3,C:\Users\espacegamers\Desktop\Master IAII\Cour...,cast_ok_0_1003.jpeg,train,ok_front,0,OK
4,C:\Users\espacegamers\Desktop\Master IAII\Cour...,cast_ok_0_1005.jpeg,train,ok_front,0,OK

Nombre d'images : 7348

## 2. Extraction des caractéristiques

Les caractéristiques utilisées sont : statistiques d'intensité, histogramme, texture GLCM, texture LBP et mesures de segmentation. Pour tester rapidement, vous pouvez mettre une valeur dans `MAX_IMAGES`.

In [3]:
MAX_IMAGES = None  # exemple rapide: 1000
features_df = build_features_dataframe(index_df, max_images=MAX_IMAGES)

output_path = FEATURES_DIR / "casting_features.csv"
save_dataframe(features_df, output_path)

print(f"Fichier sauvegardé : {output_path}")
display(features_df.head())

Extraction des caracteristiques: 100/7348
Extraction des caracteristiques: 200/7348
Extraction des caracteristiques: 300/7348
Extraction des caracteristiques: 400/7348
Extraction des caracteristiques: 500/7348
Extraction des caracteristiques: 600/7348
Extraction des caracteristiques: 700/7348
Extraction des caracteristiques: 800/7348
Extraction des caracteristiques: 900/7348
Extraction des caracteristiques: 1000/7348
Extraction des caracteristiques: 1100/7348
Extraction des caracteristiques: 1200/7348
Extraction des caracteristiques: 1300/7348
Extraction des caracteristiques: 1400/7348
Extraction des caracteristiques: 1500/7348
Extraction des caracteristiques: 1600/7348
Extraction des caracteristiques: 1700/7348
Extraction des caracteristiques: 1800/7348
Extraction des caracteristiques: 1900/7348
Extraction des caracteristiques: 2000/7348
Extraction des caracteristiques: 2100/7348
Extraction des caracteristiques: 2200/7348
Extraction des caracteristiques: 2300/7348
Extraction des caracteristiques: 2400/7348
Extraction des caracteristiques: 2500/7348
Extraction des caracteristiques: 2600/7348
Extraction des caracteristiques: 2700/7348
Extraction des caracteristiques: 2800/7348
Extraction des caracteristiques: 2900/7348
Extraction des caracteristiques: 3000/7348
Extraction des caracteristiques: 3100/7348
Extraction des caracteristiques: 3200/7348
Extraction des caracteristiques: 3300/7348
Extraction des caracteristiques: 3400/7348
Extraction des caracteristiques: 3500/7348
Extraction des caracteristiques: 3600/7348
Extraction des caracteristiques: 3700/7348
Extraction des caracteristiques: 3800/7348
Extraction des caracteristiques: 3900/7348
Extraction des caracteristiques: 4000/7348
Extraction des caracteristiques: 4100/7348
Extraction des caracteristiques: 4200/7348
Extraction des caracteristiques: 4300/7348
Extraction des caracteristiques: 4400/7348
Extraction des caracteristiques: 4500/7348
Extraction des caracteristiques: 4600/7348
Extraction des caracteristiques: 4700/7348
Extraction des caracteristiques: 4800/7348
Extraction des caracteristiques: 4900/7348
Extraction des caracteristiques: 5000/7348
Extraction des caracteristiques: 5100/7348
Extraction des caracteristiques: 5200/7348
Extraction des caracteristiques: 5300/7348
Extraction des caracteristiques: 5400/7348
Extraction des caracteristiques: 5500/7348
Extraction des caracteristiques: 5600/7348
Extraction des caracteristiques: 5700/7348
Extraction des caracteristiques: 5800/7348
Extraction des caracteristiques: 5900/7348
Extraction des caracteristiques: 6000/7348
Extraction des caracteristiques: 6100/7348
Extraction des caracteristiques: 6200/7348
Extraction des caracteristiques: 6300/7348
Extraction des caracteristiques: 6400/7348
Extraction des caracteristiques: 6500/7348
Extraction des caracteristiques: 6600/7348
Extraction des caracteristiques: 6700/7348
Extraction des caracteristiques: 6800/7348
Extraction des caracteristiques: 6900/7348
Extraction des caracteristiques: 7000/7348
Extraction des caracteristiques: 7100/7348
Extraction des caracteristiques: 7200/7348
Extraction des caracteristiques: 7300/7348
Extraction des caracteristiques: 7348/7348
Fichier sauvegardé : C:\Users\espacegamers\Desktop\Master IAII\Cours\drive-download-20251005T182208Z-1-001\S2\Traitement d_images et vision par ordinateur_\Projet\industrial-defect-detection2\data\features\casting_features.csv

,intensity_mean,intensity_std,intensity_min,intensity_max,intensity_median,intensity_p10,intensity_p90,hist_00,hist_01,hist_02,...,defect_area,defect_area_ratio,largest_defect_area,largest_defect_area_ratio,path,filename,split,class_folder,label,label_name
0,156.107742,62.096371,3.0,253.0,172.0,43.0,223.0,0.019944,0.046189,0.050100,...,14998.0,0.166644,11467.0,0.127411,C:\Users\espacegamers\Desktop\Master IAII\Cour...,cast_ok_0_1.jpeg,train,ok_front,0,OK
1,157.017288,58.785080,3.0,253.0,176.0,50.0,213.0,0.021233,0.039978,0.034711,...,26201.0,0.291122,12151.0,0.135011,C:\Users\espacegamers\Desktop\Master IAII\Cour...,cast_ok_0_1001.jpeg,train,ok_front,0,OK
2,149.712479,58.804409,2.0,249.0,168.0,41.0,204.0,0.029444,0.046744,0.038456,...,25808.0,0.286756,10709.0,0.118989,C:\Users\espacegamers\Desktop\Master IAII\Cour...,cast_ok_0_1002.jpeg,train,ok_front,0,OK
3,155.423035,62.106228,4.0,254.0,170.0,42.0,224.0,0.019167,0.043589,0.055267,...,15455.0,0.171722,11481.0,0.127567,C:\Users\espacegamers\Desktop\Master IAII\Cour...,cast_ok_0_1003.jpeg,train,ok_front,0,OK
4,161.378815,61.426872,4.0,251.0,183.0,57.0,225.0,0.016300,0.032667,0.033989,...,31703.0,0.352256,19389.0,0.215433,C:\Users\espacegamers\Desktop\Master IAII\Cour...,cast_ok_0_1005.jpeg,train,ok_front,0,OK

## 3. Vérification du dataset tabulaire

On vérifie le nombre de caractéristiques numériques et la présence des labels.

In [4]:
feature_columns = get_feature_columns(features_df)

print(f"Nombre de caractéristiques : {len(feature_columns)}")
print(feature_columns[:10])
display(features_df.groupby(["split", "label_name"]).size().reset_index(name="count"))

Nombre de caractéristiques : 50
['intensity_mean', 'intensity_std', 'intensity_min', 'intensity_max', 'intensity_median', 'intensity_p10', 'intensity_p90', 'hist_00', 'hist_01', 'hist_02']

   split label_name  count
0   test  Defective    453
1   test         OK    262
2  train  Defective   3758
3  train         OK   2875

## Conclusion

Les images sont maintenant représentées sous forme de lignes numériques. Ce format est adapté à SVM et aux autres modèles classiques.